from .modulation import Modulation
from .generic import GenericDecoder, PreambleConfig


def define_protocols():
    return [
        GenericDecoder("AlutechAT4N", 400, 800, 140, 72,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("Ansonic", 555, 1111, 120, 12,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.FSK2),
        GenericDecoder("BETT", 340, 2000, 150, 18,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="LH", mod=Modulation.OOK),
        GenericDecoder("CAME", 320, 640, 150, 12,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=56,
                       preamble_delta_mult=63, encoding="LH", mod=Modulation.OOK),
        GenericDecoder("CAME12", 320, 640, 150, 12,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=56,
                       preamble_delta_mult=63, encoding="LH", mod=Modulation.OOK),
        GenericDecoder("CAME24", 320, 640, 150, 24,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=56,
                       preamble_delta_mult=63, encoding="LH", mod=Modulation.OOK),
        GenericDecoder("CAMEAtomo", 600, 1200, 250, 62,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("CAMETwee", 500, 1000, 250, 54,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("ChamberlainCode", 1000, 3000, 200, 10,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=39,
                       encoding="HL", invert=False, mod=Modulation.OOK),
        GenericDecoder("Clemsa", 385, 2695, 150, 18,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="LH", mod=Modulation.OOK),
        GenericDecoder("DickertMAHS", 400, 800, 100, 36,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("Doitrand", 400, 1100, 150, 37,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("Dooya", 366, 733, 120, 40,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("FaacSLH", 255, 595, 100, 64,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("Feron", 350, 750, 150, 32,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("GangQi", 500, 1200, 200, 34,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("GateTX", 350, 700, 100, 24,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("Hay21", 300, 700, 150, 21,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("Hollarm", 200, 1000, 200, 42,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("Holtek", 430, 870, 100, 40,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="LH", mod=Modulation.OOK),
        GenericDecoder("HoneywellWDB", 160, 320, 60, 48,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("Hormann", 500, 1000, 200, 44,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("iDo", 450, 1450, 150, 48,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("IntertechnoV3", 275, 1375, 150, 32,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("KeeLoq", 400, 800, 140, 64,
                       preamble_type=PreambleConfig.SYNC_GAP, preamble_te_mult=10,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("KIAseed", 250, 500, 100, 61,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.FSK2),
        GenericDecoder("KingGatesStylo4k", 400, 1100, 140, 89,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("Legrand", 375, 1125, 150, 18,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="LH", mod=Modulation.OOK),
        GenericDecoder("Linear", 500, 1500, 350, 10,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("LinearDelta3", 500, 2000, 150, 8,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("Magellan", 200, 400, 100, 32,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("Marantec", 1000, 2000, 200, 49,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("Marantec24", 800, 1600, 200, 24,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("Mastercode", 1072, 2145, 150, 36,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("MegaCode", 1000, 1000, 200, 24,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("NeroRadio", 200, 400, 80, 56,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("NeroSketch", 330, 660, 150, 40,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("NiceFlo", 700, 1400, 200, 12,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="LH", mod=Modulation.OOK),
        GenericDecoder("NiceFloRS", 500, 1000, 300, 52,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("PhoenixV2", 427, 853, 100, 52,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("PowerSmart", 225, 450, 100, 64,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("Princeton", 390, 1170, 300, 24,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("ReversRB2", 250, 500, 160, 64,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("Roger", 500, 1000, 270, 28,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("ScherKhan", 750, 1100, 150, 35,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.FSK2),
        GenericDecoder("SMC5326", 300, 900, 200, 25,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", mod=Modulation.OOK),
        GenericDecoder("StarLine", 250, 500, 120, 64,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="HL", invert=True, mod=Modulation.OOK),
        GenericDecoder("SomfyTelis", 640, 1280, 250, 56,
                       preamble_type=PreambleConfig.FIXED_LOW, preamble_te_mult=36,
                       encoding="LH", mod=Modulation.OOK),
        GenericDecoder("Security+V1", 500, 1500, 100, 21,
                       preamble_type=PreambleConfig.SYNC_GAP, preamble_te_mult=120,
                       encoding="LH", mod=Modulation.OOK),
    ]
