"""
for easy key changing n stuff
"""

keys = {
        "null": chr(0), # No key pressed,
        "ERR_OVF": 0x01,
        "LCTRL": 0x01,
        "LSHIFT": 0x02,
        "LALT": 0x04,
        "LMETA": 0x08,
        "WINDOWS": 0x08, # for duckyscript
        "RCTRL": 0x10,
        "RSHIFT": 0x20,
        "RALT": 0x40,
        "RMETA": 0x80,
        "a": 0x04, # Keyboard a and A,
        "b": 0x05, # Keyboard b and B,
        "c": 0x06, # Keyboard c and C,
        "d": 0x07, # Keyboard d and D,
        "e": 0x08, # Keyboard e and E,
        "f": 0x09, # Keyboard f and F,
        "g": 0x0a, # Keyboard g and G,
        "h": 0x0b, # Keyboard h and H,
        "i": 0x0c, # Keyboard i and I,
        "j": 0x0d, # Keyboard j and J,
        "k": 0x0e, # Keyboard k and K,
        "l": 0x0f, # Keyboard l and L,
        "m": 0x10, # Keyboard m and M,
        "n": 0x11, # Keyboard n and N,
        "o": 0x12, # Keyboard o and O,
        "p": 0x13, # Keyboard p and P,
        "q": 0x14, # Keyboard q and Q,
        "r": 0x15, # Keyboard r and R,
        "s": 0x16, # Keyboard s and S,
        "t": 0x17, # Keyboard t and T,
        "u": 0x18, # Keyboard u and U,
        "v": 0x19, # Keyboard v and V,
        "w": 0x1a, # Keyboard w and W,
        "x": 0x1b, # Keyboard x and X,
        "y": 0x1c, # Keyboard y and Y,
        "z": 0x1d, # Keyboard z and Z,
        "1": 0x1e, # Keyboard 1 and !,
        "2": 0x1f, # Keyboard 2 and @,
        "3": 0x20, # Keyboard 3 and ,
        "4": 0x21, # Keyboard 4 and $,
        "5": 0x22, # Keyboard 5 and %,
        "6": 0x23, # Keyboard 6 and ^,
        "7": 0x24, # Keyboard 7 and &,
        "8": 0x25, # Keyboard 8 and *,
        "9": 0x26, # Keyboard 9 and (,
        "0": 0x27, # Keyboard 0 and ),
        "ENTER": 0x28, # Keyboard Return (ENTER),
        "ESC": 0x29, # Keyboard ESCAPE,
        "BACKSPACE": 0x2a, # Keyboard DELETE (Backspace),
        "TAB": 0x2b, # Keyboard Tab,
        " ": 0x2c, # Keyboard Spacebar,
        "-": 0x2d, # Keyboard - and _,
        "=": 0x2e, # Keyboard = and +,
        "[": 0x2f, # Keyboard [ and {,
        "]": 0x30, # Keyboard ] and },
        "\\": 0x31, # Keyboard \ and |,
        "~": 0x32, # Keyboard Non-US  and ~,
        ";": 0x33, # Keyboard ; and :,
        "'": 0x34, # Keyboard ' and ",
        "`": 0x35, # Keyboard ` and ~,
        ",": 0x36, # Keyboard , and <,
        ".": 0x37, # Keyboard . and >,
        "/": 0x38, # Keyboard / and ?,
        "CAPSLOCK": 0x39, # Keyboard Caps Lock,
        "F1": 0x3a, # Keyboard F1,
        "F2": 0x3b, # Keyboard F2,
        "F3": 0x3c, # Keyboard F3,
        "F4": 0x3d, # Keyboard F4,
        "F5": 0x3e, # Keyboard F5,
        "F6": 0x3f, # Keyboard F6,
        "F7": 0x40, # Keyboard F7,
        "F8": 0x41, # Keyboard F8,
        "F9": 0x42, # Keyboard F9,
        "F10": 0x43, # Keyboard F10,
        "F11": 0x44, # Keyboard F11,
        "F12": 0x45, # Keyboard F12,
        "SYSRQ": 0x46, # Keyboard 
        "SCROLLLOCK": 0x47, # Keyboard Scroll Lock,
        "PAUSE": 0x48, # Keyboard Pause,
        "INSERT": 0x49, # Keyboard Insert,
        "HOME": 0x4a, # Keyboard Home,
        "PAGEUP": 0x4b, # Keyboard Page Up,
        "DELETE": 0x4c, # Keyboard Delete Forward,
        "END": 0x4d, # Keyboard End,
        "PAGEDOWN": 0x4e, # Keyboard Page Down,
        "RIGHT": 0x4f, # Keyboard Right Arrow,
        "LEFT": 0x50, # Keyboard Left Arrow,
        "DOWN": 0x51, # Keyboard Down Arrow,
        "UP": 0x52, # Keyboard Up Arrow,
        "NUMLOCK": 0x53, # Keyboard Num Lock and Clear,
        "KPSLASH": 0x54, # Keypad /,
        "KPASTERISK": 0x55, # Keypad *,
        "KPENTER": 0x58, # Keypad ENTER,
        "KP1": 0x59, # Keypad 1 and End,
        "KP2": 0x5a, # Keypad 2 and Down Arrow,
        "KP3": 0x5b, # Keypad 3 and PageDn,
        "KP4": 0x5c, # Keypad 4 and Left Arrow,
        "KP5": 0x5d, # Keypad 5,
        "KP6": 0x5e, # Keypad 6 and Right Arrow,
        "KP7": 0x5f, # Keypad 7 and Home,
        "KP8": 0x60, # Keypad 8 and Up Arrow,
        "KP9": 0x61, # Keypad 9 and Page Up,
        "KP0": 0x62, # Keypad 0 and Insert,
        "KPDOT": 0x63, # Keypad . and Delete,
        "102ND": 0x64, # Keyboard Non-US \ and |,
        "COMPOSE": 0x65, # Keyboard Application,
        "POWER": 0x66, # Keyboard Power,
        "F13": 0x68, # Keyboard F13,
        "F14": 0x69, # Keyboard F14,
        "F15": 0x6a, # Keyboard F15,
        "F16": 0x6b, # Keyboard F16,
        "F17": 0x6c, # Keyboard F17,
        "F18": 0x6d, # Keyboard F18,
        "F19": 0x6e, # Keyboard F19,
        "F20": 0x6f, # Keyboard F20,
        "F21": 0x70, # Keyboard F21,
        "F22": 0x71, # Keyboard F22,
        "F23": 0x72, # Keyboard F23,
        "F24": 0x73, # Keyboard F24,
        "OPEN": 0x74, # Keyboard Execute,
        "HELP": 0x75, # Keyboard Help,
        "PROPS": 0x76, # Keyboard Menu,
        "FRONT": 0x77, # Keyboard Select,
        "STOP": 0x78, # Keyboard Stop,
        "AGAIN": 0x79, # Keyboard Again,
        "UNDO": 0x7a, # Keyboard Undo,
        "CUT": 0x7b, # Keyboard Cut,
        "COPY": 0x7c, # Keyboard Copy,
        "PASTE": 0x7d, # Keyboard Paste,
        "FIND": 0x7e, # Keyboard Find,
        "MUTE": 0x7f, # Keyboard Mute,
        "VOLUMEUP": 0x80, # Keyboard Volume Up,
        "VOLUMEDOWN": 0x81, # Keyboard Volume Down,
    }

shifted = {
        # shifted chars (shift requiered)
        "\"": [0x34], # Keyboard "
        "!": [0x1e], # Keyboard 1 and !,
        "@": [0x1f], # Keyboard 2 and @,
        "#": [0x20], # Keyboard 3 and ,
        "$": [0x21], # Keyboard 4 and $,
        "%": [0x22], # Keyboard 5 and %,
        "^": [0x23], # Keyboard 6 and ^,
        "&": [0x24], # Keyboard 7 and &,
        "*": [0x25], # Keyboard 8 and *,
        "(": [0x26], # Keyboard 9 and (,
        ")": [0x27], # Keyboard 0 and ),
        ":": [0x33], # Keyboard ; and :
        "|": [0x31], # Keyboard \ and |,
        ">": [0x37], # Keyboard . and >,
        "{": [0x2f], # Keyboard [ and {,
        "}": [0x30], # Keyboard ] and },
        "<": [0x36], # Keyboard , and <,
        "_": [0x2d], # Keyboard - and _,
        "+": [0x2e], # Keyboard = and +,
    }

symbols = [
        # symbols (or anything) that dont need shift
        '-',
        '=',
        '[',
        ']',
        '\\',
        ';',
        "'",
        ',',
        '.',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '0',
        '/'
        ]
